# Generated by Django 3.2.2 on 2021-06-15 22:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comuna',
            fields=[
                ('id_comuna', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_com', models.CharField(max_length=100, verbose_name='Comuna')),
                ('zona_com', models.CharField(blank=True, max_length=100, verbose_name='Zona')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Corte',
            fields=[
                ('id_corte', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_cor', models.CharField(max_length=100, verbose_name='Corte')),
                ('descripcion_cor', models.CharField(blank=True, max_length=100, verbose_name='Descripcion')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='EstadoDiseno',
            fields=[
                ('id_estado', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_est', models.CharField(max_length=100, verbose_name='Estado Diseño')),
                ('valor_est', models.IntegerField(default=0, verbose_name='Valor Estado')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Existe',
            fields=[
                ('id_existe', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_exi', models.CharField(max_length=20, verbose_name='Existe')),
                ('valor_exi', models.IntegerField(default=0, verbose_name='Valor')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='PeriodoCarga',
            fields=[
                ('id_periodo', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_per', models.DateField(verbose_name='Fecha Periodo Carga')),
                ('nombre_per', models.CharField(blank=True, max_length=100, verbose_name='Periodo')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Riesgo',
            fields=[
                ('id_riesgo', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_rie', models.CharField(max_length=20, verbose_name='Riesgo')),
                ('valor_rie', models.IntegerField(default=0, verbose_name='Valor')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='TipoCierre',
            fields=[
                ('id_tcierre', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_tci', models.CharField(max_length=100, verbose_name='Tipo Cierre')),
                ('valor_tci', models.IntegerField(default=0, verbose_name='Valor TipoCierre')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Ubicacion',
            fields=[
                ('id_ubicacion', models.AutoField(primary_key=True, serialize=False)),
                ('bip_ubi', models.CharField(blank=True, max_length=8, verbose_name='BIP')),
                ('direccion_ubi', models.CharField(blank=True, max_length=100, verbose_name='Direccion')),
                ('latitud_ubi', models.IntegerField(null=True, verbose_name='Latitud')),
                ('longitud_ubi', models.IntegerField(null=True, verbose_name='Longitud')),
                ('unidad_destino_ubi', models.CharField(blank=True, max_length=100, verbose_name='Unidad Destino')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('comuna_ubi', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='crud.comuna', verbose_name='Comuna')),
                ('corte_ubi', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='crud.corte', verbose_name='Corte')),
            ],
        ),
        migrations.CreateModel(
            name='Eval_Terrenos',
            fields=[
                ('id_eval_terrenos', models.AutoField(primary_key=True, serialize=False)),
                ('m2_inscripcion_ter', models.IntegerField(blank=True, default=0, null=True, verbose_name='M2')),
                ('fecha_ini_diseno_ter', models.DateField(auto_now=True, verbose_name='Fecha Inicio Diseño')),
                ('fecha_constru_ter', models.DateField(auto_now=True, verbose_name='Fecha Construccion')),
                ('fecha_entrega_ter', models.DateField(auto_now=True, verbose_name='Fecha Entrega')),
                ('fecha_compra_ter', models.DateField(auto_now=True, verbose_name='Fecha Compra')),
                ('monto_uf_ter', models.IntegerField(blank=True, null=True, verbose_name='Monto UF')),
                ('obs_ter', models.CharField(blank=True, max_length=100, verbose_name='Observacion')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('estadodiseno_ter', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='estadodiseno', to='crud.estadodiseno', verbose_name='Estado Diseño')),
                ('existe_constru_ter', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ExisteConstru', to='crud.existe', verbose_name='Existe Construccion')),
                ('existe_enuso_ter', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ExisteEnUso', to='crud.existe', verbose_name='Existe En Uso')),
                ('existe_gasto_ter', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ExisteGasto', to='crud.existe', verbose_name='Existe Gasto')),
                ('existe_guaria_ter', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ExisteGuardia', to='crud.existe', verbose_name='Existe Guardia')),
                ('fecha_carga_ter', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='crud.periodocarga')),
                ('riesgo_incendio_ter', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Incendio', to='crud.riesgo', verbose_name='Riesgo Incendio')),
                ('riesgo_intrusion_ter', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Intrusion', to='crud.riesgo', verbose_name='Riesgo Intrusion')),
                ('ubicacion_ter', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='crud.ubicacion', verbose_name='BIP')),
            ],
        ),
    ]
