# Generated by Django 3.2.2 on 2021-06-16 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0002_eval_terrenos_kpi'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eval_terrenos',
            name='fecha_compra_ter',
            field=models.DateField(verbose_name='Fecha Compra'),
        ),
        migrations.AlterField(
            model_name='eval_terrenos',
            name='fecha_constru_ter',
            field=models.DateField(verbose_name='Fecha Construccion'),
        ),
        migrations.AlterField(
            model_name='eval_terrenos',
            name='fecha_entrega_ter',
            field=models.DateField(verbose_name='Fecha Entrega'),
        ),
        migrations.AlterField(
            model_name='eval_terrenos',
            name='fecha_ini_diseno_ter',
            field=models.DateField(verbose_name='Fecha Inicio Diseño'),
        ),
    ]
