# Generated by Django 3.2.2 on 2021-06-16 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0004_alter_eval_terrenos_fecha_ini_diseno_ter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eval_terrenos',
            name='fecha_compra_ter',
            field=models.DateField(null=True, verbose_name='Fecha Compra'),
        ),
        migrations.AlterField(
            model_name='eval_terrenos',
            name='fecha_constru_ter',
            field=models.DateField(null=True, verbose_name='Fecha Construccion'),
        ),
        migrations.AlterField(
            model_name='eval_terrenos',
            name='fecha_entrega_ter',
            field=models.DateField(null=True, verbose_name='Fecha Entrega'),
        ),
    ]
